### ISSUE TITLE
Hello bhai yeh sab kya h

### ISSUE THREAD

**Issue by DiviyamPathak** [Sunilkj8/Story#1]
Sab thik toh hai na kuch hoga toh bolana dost samjhna apna

**Comment by Sunilkj8** [comment]
Saale tu github se mail kr rha h mene socha tujhe email kaha se mili

**Comment by DiviyamPathak** [comment]
Abei Instagram pr tune apna daal hi rakha h

**Comment by DiviyamPathak** [comment]
Per hu kya h bhai yeh sab kya h 😁😁 Tu kuch likh rha h kya?
